version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=ayush
      - POSTGRES_PASSWORD=hackathon_secret
      - POSTGRES_DB=ayur_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ayush:hackathon_secret@db/ayur_db
    depends_on:
      - db

volumes:
  postgres_data: