name: Python Application CI

# This workflow runs on pushes to the main branch or pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
    # Step 1: Check out your repository code
    - uses: actions/checkout@v4

    # Step 2: Build and start your Docker containers in the background
    - name: Build and run containers
      run: docker-compose up --build -d

    # Step 3: Wait for the database to be ready
    # A simple sleep is often enough for a test environment
    - name: Wait for database
      run: sleep 10

    # Step 4: Run your tests!
    # This is the same command you've been running locally
    - name: Run Pytest
      run: docker-compose exec api pytest
